# 02-configure-gitea.yml
---
- name: Zone 1 Management - Decoupled Gitea Deployment
  hosts: sn-devops-gitea
  become: true
  vars:
    gitea_db_host: "172.16.30.109:5432"
  tasks:
    - name: Enforce App Configuration (app.ini)
      ansible.builtin.copy:
        dest: /etc/gitea/app.ini
        owner: root
        group: root
        mode: '0640'
        content: |
          [server]
          APP_NAME = TMinus36 Enterprise GitOps
          RUN_USER = git
          RUN_MODE = prod
          SSH_DOMAIN = 10.0.0.104
          DOMAIN = gitea.att.local
          HTTP_PORT = 3000
          ROOT_URL = http://gitea.att.local:3000/
          DISABLE_SSH = false
          SSH_PORT = 22

          [database]
          DB_TYPE = postgres
          HOST = {{ gitea_db_host }}
          NAME = giteadb
          USER = gitea_admin
          PASSWD = {{ vault_gitea_db_pass }}