# 05-configure-guacamole.yml
---
- name: Zone 2 Access Gateway - Guacamole Deployment
  hosts: sn-guacamole-gateway
  become: true
  vars:
    guac_db_host: "172.16.30.109"
  tasks:
    - name: Deploy Guacamole Properties
      ansible.builtin.copy:
        dest: /etc/guacamole/guacamole.properties
        owner: root
        group: root
        mode: '0640'
        content: |
          guacd-hostname: localhost
          guacd-port: 4822

          postgresql-hostname: {{ guac_db_host }}
          postgresql-port: 5432
          postgresql-database: guacamoledb
          postgresql-username: guac_admin
          postgresql-password: {{ vault_guac_db_pass }}

          openid-authorization-endpoint: https://auth.att.local/application/o/authorize/
          openid-jwks-endpoint: https://auth.att.local/application/o/guacamole/jwks/
          openid-issuer: https://auth.att.local/application/o/guacamole/
          openid-client-id: {{ vault_guac_oidc_client_id }}
          openid-redirect-uri: https://guac.att.local/
          openid-username-claim-type: preferred_username