# 04-configure-authentik.yml
---
- name: Zone 2 Identity Provider - Authentik Deployment
  hosts: sn-auth-authentik
  become: true
  vars:
    authentik_db_host: "172.16.30.109"
  tasks:
    - name: Deploy Authentik Environment Configuration
      ansible.builtin.copy:
        dest: /opt/authentik/.env
        owner: root
        group: root
        mode: '0600'
        content: |
          AUTHENTIK_POSTGRESQL__HOST={{ authentik_db_host }}
          AUTHENTIK_POSTGRESQL__NAME=authentik
          AUTHENTIK_POSTGRESQL__USER=authentik_admin
          AUTHENTIK_POSTGRESQL__PASSWORD={{ vault_authentik_db_pass }}
          AUTHENTIK_REDIS__HOST=localhost
          AUTHENTIK_SECRET_KEY={{ vault_authentik_secret_key }}
          AUTHENTIK_ERROR_REPORTING__ENABLED=false
          AUTHENTIK_DISABLE_UPDATE_CHECK=true