# File: inventory/hosts.ini
# Updated with Proxmox-verified IPs

[zone_1_management]
10.10.0.101 ansible_user=root # sn-devops-gitea (LXC 104)

[zone_2_edge]
10.0.0.105 ansible_user=root # sn-edge-proxy
10.0.0.107 ansible_user=root # sn-guacamole-gateway

[zone_3_data]
172.16.30.103 ansible_user=root # sn-db-postgres
172.16.30.104 ansible_user=root # sn-vault-secrets (LXC 110 - Ensure IP is 172.16.30.104)

[zone_4_security]
172.16.40.200 ansible_user=root # sn-wazuh-siem

[zone_5_observability]
172.16.50.111 ansible_user=root # sn-loki-tsdb
172.16.50.112 ansible_user=root # sn-prometheus-metrics
172.16.50.113 ansible_user=root # sn-grafana-ui

[support_plane:children]
zone_1_management
zone_2_edge
zone_3_data
zone_4_security
zone_5_observability